### ISSUE TITLE
scipion-app 3.6.0: ./scipion3 config no longer working

### ISSUE THREAD

**Issue by woutdenolf** [scipion-em/scipion-app#194]
Install

```bash
conda create -y -n scipion_installer python~=3.9.0 pip
conda activate scipion_installer
pip install scipion-installer
mkdir -p /home/denolf/tmp
python -m scipioninstaller -conda -noXmipp -noAsk /home/denolf/tmp
```

Reproduce issue

```
./scipion3 config --overwrite --unattended
```

Traceback

```
Scipion v3.6.0 - Eugenius
/home/denolf/tmp/scipion/config/scipion.conf scipion
* Creating backup: /home/denolf/tmp/scipion/config/backups/scipion.conf.20240807095645
* Creating configuration file: /home/denolf/tmp/scipion/config/scipion.conf
Please edit it to reflect the configuration of your system.

Config error: Missing file: /users/denolf/.local/wdnbashutils/virtualenvs/scipion3/lib/python3.8/site-packages/scipion/templates/scipion.template

Traceback (most recent call last):
  File "/users/denolf/.local/wdnbashutils/virtualenvs/scipion3/lib/python3.8/site-packages/scipion/scripts/config.py", line 140, in main
    createConf(fpath, join(templates_dir, getTemplateName(tmplt)),
  File "/users/denolf/.local/wdnbashutils/virtualenvs/scipion3/lib/python3.8/site-packages/scipion/scripts/config.py", line 200, in createConf
    raise FileNotFoundError('Missing file: %s' % ftemplate)
FileNotFoundError: Missing file: /users/denolf/.local/wdnbashutils/virtualenvs/scipion3/lib/python3.8/site-packages/scipion/templates/scipion.template
```

**Comment by woutdenolf** [comment]
Template was removed here: https://github.com/scipion-em/scipion-app/pull/192

**Comment by azazellochg** [comment]
Fixed in https://github.com/scipion-em/scipion-app/pull/195

**Comment by woutdenolf** [comment]
I can confirm the fix.
