### ISSUE TITLE
no such key in json plugin file

### ISSUE THREAD

**Issue by azazellochg** [scipion-em/scipion-app#21]
```
Exception in thread loading_plugin:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/azazello/soft/scipion3/scipion-app/scipion/install/plugin_manager.py", line 911, in loadPlugins
    pluginDict = pluginRepo.getPlugins(getPipData=True)
  File "/home/azazello/soft/scipion3/scipion-app/scipion/install/plugin_funcs.py", line 480, in getPlugins
    pluginsJson[pluginName].update(pluginSourceUrl=pluginsJson[pluginName]['pluginSourceUrl'])
KeyError: 'pluginSourceUrl'
```

**Comment by azazellochg** [comment]
Fixed in https://github.com/scipion-em/scipion-app/pull/23/commits/00668bfa1bb08710b95aef9f9bc90b71e9ccc1e2
